variables:
  - name: BuildParameters.RestoreBuildProjects
    value: '**/*.csproj'
  - name: BuildParameters.TestProjects
    value: '**/*[Tt]ests/*.csproj'
  - name: BuildConfiguration
    value: 'Release'

trigger:
  branches:
    include:
      - main
  batch: true

name: $(date:yyyyMMdd)$(rev:.r)

jobs:
- job: BuildAndTest
  displayName: Build, Test, and Publish Job
  pool:
    vmImage: 'windows-latest'

  steps:
    - checkout: self
      fetchDepth: 1

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '$(BuildParameters.RestoreBuildProjects)'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '$(BuildParameters.RestoreBuildProjects)'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: '$(BuildParameters.TestProjects)'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        projects: '$(BuildParameters.RestoreBuildProjects)'
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'