// <auto-generated />
using System;
using AssetManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagement.Data.Migrations
{
    [DbContext(typeof(AssetManagementDbContext))]
    [Migration("20250521110458_UpdateAssetEntitySeed")]
    partial class UpdateAssetEntitySeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManagement.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("InstallDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModificatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModificatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryId1");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174001"),
                            AssetCode = "LAP-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174005"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2023, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 1,
                            Name = "Dell XPS 13",
                            Specification = "Intel i7, 16GB RAM, 512GB SSD",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174002"),
                            AssetCode = "LAP-002",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174005"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 2,
                            Name = "MacBook Pro 14",
                            Specification = "M1 Pro, 32GB RAM, 1TB SSD",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174003"),
                            AssetCode = "MON-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174007"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2022, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 1,
                            Name = "Dell UltraSharp 27",
                            Specification = "27-inch, 4K, IPS Panel",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174004"),
                            AssetCode = "MON-002",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174007"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2023, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 1,
                            Name = "LG 32GN600",
                            Specification = "32-inch, QHD, 144Hz",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174005"),
                            AssetCode = "IPD-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174003"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2023, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 2,
                            Name = "iPad Pro 12.9",
                            Specification = "M2 Chip, 256GB, Wi-Fi",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174006"),
                            AssetCode = "IPD-002",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174003"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 3,
                            Name = "iPad Air 5",
                            Specification = "M1 Chip, 64GB, Wi-Fi",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174007"),
                            AssetCode = "IPH-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174004"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 1,
                            Name = "iPhone 14 Pro",
                            Specification = "256GB, Black, 5G",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174008"),
                            AssetCode = "MOU-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174001"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 2,
                            Name = "Logitech MX Master 3",
                            Specification = "Wireless, 4000 DPI, Ergonomic",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174009"),
                            AssetCode = "HST-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174002"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2024, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 1,
                            Name = "Sony WH-1000XM5",
                            Specification = "Wireless, Noise-Cancelling, 30hr Battery",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174010"),
                            AssetCode = "PC-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174008"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2020, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 3,
                            Name = "HP EliteDesk 800",
                            Specification = "Intel i5, 8GB RAM, 1TB HDD",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174011"),
                            AssetCode = "TAB-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174009"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2024, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 2,
                            Name = "Samsung Galaxy Tab S8",
                            Specification = "Snapdragon 8, 128GB, 11-inch",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174012"),
                            AssetCode = "MOB-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174006"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 3,
                            Name = "Samsung Galaxy S23",
                            Specification = "256GB, 5G, Snapdragon 8 Gen 2",
                            State = 1
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModificatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModificatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174001"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bluetooth Mouse",
                            Slug = "Bluetooth Mouse"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174002"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Headset",
                            Slug = "Headset"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174003"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ipad",
                            Slug = "Ipad"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174004"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Iphone",
                            Slug = "Iphone"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174005"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laptop",
                            Slug = "Laptop"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174006"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mobile",
                            Slug = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174007"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Monitor",
                            Slug = "Monitor"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174008"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Personal Computer",
                            Slug = "Personal Computer"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174009"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tablet",
                            Slug = "Tablet"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPasswordUpdated")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModificatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModificatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c87d8f20-c381-4970-b367-09f2cf95d655"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nghiadinh@example.com",
                            FirstName = "Nghia",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = false,
                            JoinedDate = new DateTimeOffset(new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Dinh",
                            Location = 1,
                            Password = "g7/Bvucy8BU+fYIA9ibE0gACIvZ6mPvm7Jf8EBXicQUgjeTEUvSyt1KrLXUPZmGW",
                            StaffCode = "SD0001",
                            Type = 1,
                            Username = "nghiadinh"
                        },
                        new
                        {
                            Id = new Guid("1f2b0a56-3c8e-4771-b227-69e2cd5e41a3"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "minhnguyen@example.com",
                            FirstName = "Minh",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = false,
                            JoinedDate = new DateTimeOffset(new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen",
                            Location = 1,
                            Password = "g7/Bvucy8BU+fYIA9ibE0gACIvZ6mPvm7Jf8EBXicQUgjeTEUvSyt1KrLXUPZmGW",
                            StaffCode = "SD0002",
                            Type = 2,
                            Username = "minhnguyen"
                        },
                        new
                        {
                            Id = new Guid("2b6d4d81-7305-4cd3-9104-760aa2d9b80a"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1994, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "linhtran@example.com",
                            FirstName = "Linh",
                            Gender = 2,
                            IsActive = true,
                            IsPasswordUpdated = false,
                            JoinedDate = new DateTimeOffset(new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tran",
                            Location = 1,
                            Password = "g7/Bvucy8BU+fYIA9ibE0gACIvZ6mPvm7Jf8EBXicQUgjeTEUvSyt1KrLXUPZmGW",
                            StaffCode = "SD0003",
                            Type = 2,
                            Username = "linhtran"
                        },
                        new
                        {
                            Id = new Guid("3c57b69c-d9a0-4678-b94f-ad4533be6e81"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tuanpham@example.com",
                            FirstName = "Tuan",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = false,
                            JoinedDate = new DateTimeOffset(new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Pham",
                            Location = 3,
                            Password = "g7/Bvucy8BU+fYIA9ibE0gACIvZ6mPvm7Jf8EBXicQUgjeTEUvSyt1KrLXUPZmGW",
                            StaffCode = "SD0004",
                            Type = 2,
                            Username = "tuanpham"
                        },
                        new
                        {
                            Id = new Guid("4f38d797-4168-4c55-8884-76f1f2d3f79b"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1993, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hoale@example.com",
                            FirstName = "Hoa",
                            Gender = 2,
                            IsActive = false,
                            IsPasswordUpdated = false,
                            JoinedDate = new DateTimeOffset(new DateTime(2020, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Le",
                            Location = 1,
                            Password = "g7/Bvucy8BU+fYIA9ibE0gACIvZ6mPvm7Jf8EBXicQUgjeTEUvSyt1KrLXUPZmGW",
                            StaffCode = "SD0005",
                            Type = 2,
                            Username = "hoale"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Asset", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Entities.Category", null)
                        .WithMany("Assets")
                        .HasForeignKey("CategoryId1");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Category", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
