// <auto-generated />
using System;
using AssetManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagement.Data.Migrations
{
    [DbContext(typeof(AssetManagementDbContext))]
    [Migration("20250520032028_UpdateUser")]
    partial class UpdateUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManagement.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModificatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModificatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPasswordUpdated")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModificatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModificatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c87d8f20-c381-4970-b367-09f2cf95d655"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nghiadinh@example.com",
                            FirstName = "Nghia",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = false,
                            JoinedDate = new DateTimeOffset(new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Dinh",
                            Location = 1,
                            Password = "g7/Bvucy8BU+fYIA9ibE0gACIvZ6mPvm7Jf8EBXicQUgjeTEUvSyt1KrLXUPZmGW",
                            StaffCode = "SD0001",
                            Type = 1,
                            Username = "nghiadinh"
                        },
                        new
                        {
                            Id = new Guid("1f2b0a56-3c8e-4771-b227-69e2cd5e41a3"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "minhnguyen@example.com",
                            FirstName = "Minh",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = false,
                            JoinedDate = new DateTimeOffset(new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen",
                            Location = 1,
                            Password = "g7/Bvucy8BU+fYIA9ibE0gACIvZ6mPvm7Jf8EBXicQUgjeTEUvSyt1KrLXUPZmGW",
                            StaffCode = "SD0002",
                            Type = 2,
                            Username = "minhnguyen"
                        },
                        new
                        {
                            Id = new Guid("2b6d4d81-7305-4cd3-9104-760aa2d9b80a"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1994, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "linhtran@example.com",
                            FirstName = "Linh",
                            Gender = 2,
                            IsActive = true,
                            IsPasswordUpdated = false,
                            JoinedDate = new DateTimeOffset(new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tran",
                            Location = 1,
                            Password = "g7/Bvucy8BU+fYIA9ibE0gACIvZ6mPvm7Jf8EBXicQUgjeTEUvSyt1KrLXUPZmGW",
                            StaffCode = "SD0003",
                            Type = 2,
                            Username = "linhtran"
                        },
                        new
                        {
                            Id = new Guid("3c57b69c-d9a0-4678-b94f-ad4533be6e81"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tuanpham@example.com",
                            FirstName = "Tuan",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = false,
                            JoinedDate = new DateTimeOffset(new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Pham",
                            Location = 3,
                            Password = "g7/Bvucy8BU+fYIA9ibE0gACIvZ6mPvm7Jf8EBXicQUgjeTEUvSyt1KrLXUPZmGW",
                            StaffCode = "SD0004",
                            Type = 2,
                            Username = "tuanpham"
                        },
                        new
                        {
                            Id = new Guid("4f38d797-4168-4c55-8884-76f1f2d3f79b"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1993, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hoale@example.com",
                            FirstName = "Hoa",
                            Gender = 2,
                            IsActive = false,
                            IsPasswordUpdated = false,
                            JoinedDate = new DateTimeOffset(new DateTime(2020, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Le",
                            Location = 1,
                            Password = "g7/Bvucy8BU+fYIA9ibE0gACIvZ6mPvm7Jf8EBXicQUgjeTEUvSyt1KrLXUPZmGW",
                            StaffCode = "SD0005",
                            Type = 2,
                            Username = "hoale"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
