// <auto-generated />
using System;
using AssetManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagement.Data.Migrations
{
    [DbContext(typeof(AssetManagementDbContext))]
    partial class AssetManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManagement.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("InstallDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModificatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModificatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryId1");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174001"),
                            AssetCode = "LAP-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174005"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2023, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 1,
                            Name = "Dell XPS 13",
                            Specification = "Intel i7, 16GB RAM, 512GB SSD",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174002"),
                            AssetCode = "LAP-002",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174005"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 2,
                            Name = "MacBook Pro 14",
                            Specification = "M1 Pro, 32GB RAM, 1TB SSD",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174003"),
                            AssetCode = "MON-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174007"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2022, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 1,
                            Name = "Dell UltraSharp 27",
                            Specification = "27-inch, 4K, IPS Panel",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174004"),
                            AssetCode = "MON-002",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174007"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2023, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 1,
                            Name = "LG 32GN600",
                            Specification = "32-inch, QHD, 144Hz",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174005"),
                            AssetCode = "IPD-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174003"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2023, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 2,
                            Name = "iPad Pro 12.9",
                            Specification = "M2 Chip, 256GB, Wi-Fi",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174006"),
                            AssetCode = "IPD-002",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174003"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 3,
                            Name = "iPad Air 5",
                            Specification = "M1 Chip, 64GB, Wi-Fi",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174007"),
                            AssetCode = "IPH-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174004"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 1,
                            Name = "iPhone 14 Pro",
                            Specification = "256GB, Black, 5G",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174008"),
                            AssetCode = "MOU-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174001"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 2,
                            Name = "Logitech MX Master 3",
                            Specification = "Wireless, 4000 DPI, Ergonomic",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174009"),
                            AssetCode = "HST-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174002"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2024, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 1,
                            Name = "Sony WH-1000XM5",
                            Specification = "Wireless, Noise-Cancelling, 30hr Battery",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174010"),
                            AssetCode = "PC-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174008"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2020, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 3,
                            Name = "HP EliteDesk 800",
                            Specification = "Intel i5, 8GB RAM, 1TB HDD",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174011"),
                            AssetCode = "TAB-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174009"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2024, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 2,
                            Name = "Samsung Galaxy Tab S8",
                            Specification = "Snapdragon 8, 128GB, 11-inch",
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("223e4567-e89b-12d3-a456-426614174012"),
                            AssetCode = "MOB-001",
                            CategoryId = new Guid("123e4567-e89b-12d3-a456-426614174006"),
                            CreatedDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstallDate = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 3,
                            Name = "Samsung Galaxy S23",
                            Specification = "256GB, 5G, Snapdragon 8 Gen 2",
                            State = 1
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174001"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bluetooth Mouse",
                            Slug = "Bluetooth Mouse"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174002"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Headset",
                            Slug = "Headset"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174003"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ipad",
                            Slug = "Ipad"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174004"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Iphone",
                            Slug = "Iphone"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174005"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laptop",
                            Slug = "Laptop"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174006"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mobile",
                            Slug = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174007"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Monitor",
                            Slug = "Monitor"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174008"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Personal Computer",
                            Slug = "Personal Computer"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174009"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModificatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tablet",
                            Slug = "Tablet"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPasswordUpdated")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c87d8f20-c381-4970-b367-09f2cf95d655"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nghia",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Dinh",
                            Location = 1,
                            Password = "SXiTq48SSiVAhIjU3TW8PHbHJ2K2geU8aoV10m9y643uUGO1pI/m7s0d5pciA0bd",
                            StaffCode = "SD0001",
                            Type = 1,
                            Username = "nghiadinh"
                        },
                        new
                        {
                            Id = new Guid("1f2b0a56-3c8e-4771-b227-69e2cd5e41a3"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Minh",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen",
                            Location = 2,
                            Password = "SXiTq48SSiVAhIjU3TW8PHbHJ2K2geU8aoV10m9y643uUGO1pI/m7s0d5pciA0bd",
                            StaffCode = "SD0002",
                            Type = 1,
                            Username = "minhnguyen"
                        },
                        new
                        {
                            Id = new Guid("2b6d4d81-7305-4cd3-9104-760aa2d9b80a"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1994, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Linh",
                            Gender = 2,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tran",
                            Location = 1,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0003",
                            Type = 2,
                            Username = "linhtran"
                        },
                        new
                        {
                            Id = new Guid("3c57b69c-d9a0-4678-b94f-ad4533be6e81"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tuan",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Pham",
                            Location = 3,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0004",
                            Type = 2,
                            Username = "tuanpham"
                        },
                        new
                        {
                            Id = new Guid("4f38d797-4168-4c55-8884-76f1f2d3f79b"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1993, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hoa",
                            Gender = 2,
                            IsActive = false,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2020, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Le",
                            Location = 1,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0005",
                            Type = 2,
                            Username = "hoale"
                        },
                        new
                        {
                            Id = new Guid("6abd3850-93f5-458a-94ed-4ccd3cb903df"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "An",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen",
                            Location = 1,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0006",
                            Type = 2,
                            Username = "annguyen"
                        },
                        new
                        {
                            Id = new Guid("d445a21d-93a2-4d4e-b1e4-421717680965"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Minh",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tran",
                            Location = 1,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0007",
                            Type = 2,
                            Username = "minhtran"
                        },
                        new
                        {
                            Id = new Guid("2b1dc1f3-945e-444d-b68d-52e59d0e699c"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1994, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Linh",
                            Gender = 2,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2022, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Pham",
                            Location = 1,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0008",
                            Type = 2,
                            Username = "linhpham"
                        },
                        new
                        {
                            Id = new Guid("88108306-c04f-4ab4-be0b-2ed7a813043d"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1989, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tuan",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2019, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Le",
                            Location = 1,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0009",
                            Type = 2,
                            Username = "tuanle"
                        },
                        new
                        {
                            Id = new Guid("2246b919-73f8-44f2-bcc2-80149e40a796"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1995, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Trang",
                            Gender = 2,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2021, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Do",
                            Location = 1,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0010",
                            Type = 2,
                            Username = "trangdo"
                        },
                        new
                        {
                            Id = new Guid("91a21848-2258-4cff-b6a8-31e75ec69ed0"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Khanh",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2020, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Vo",
                            Location = 1,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0011",
                            Type = 2,
                            Username = "khanhvo"
                        },
                        new
                        {
                            Id = new Guid("dbf2b2c5-52a7-46ea-808d-e29538529105"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1996, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thao",
                            Gender = 2,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen",
                            Location = 1,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0012",
                            Type = 2,
                            Username = "thaonguyen"
                        },
                        new
                        {
                            Id = new Guid("00b68283-d752-4fff-be4c-a0031a787876"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1993, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hieu",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Pham",
                            Location = 1,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0013",
                            Type = 2,
                            Username = "hieupham"
                        },
                        new
                        {
                            Id = new Guid("f74f2293-213d-41f3-b146-7dd4acb5499c"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1988, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lan",
                            Gender = 2,
                            IsActive = false,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2017, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen",
                            Location = 1,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0014",
                            Type = 2,
                            Username = "lannguyen"
                        },
                        new
                        {
                            Id = new Guid("edaa920f-f98e-40a8-88ab-56ffe9e99093"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Duy",
                            Gender = 1,
                            IsActive = false,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2016, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hoang",
                            Location = 1,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0015",
                            Type = 2,
                            Username = "duyhoang"
                        },
                        new
                        {
                            Id = new Guid("edf1b40d-c5e2-410b-859e-ec29a5d95292"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Binh",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tran",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0016",
                            Type = 2,
                            Username = "binhtran"
                        },
                        new
                        {
                            Id = new Guid("024e81ce-ef22-458b-bf29-e6b3bfec2fb8"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1993, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ha",
                            Gender = 2,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0017",
                            Type = 2,
                            Username = "hanguyen"
                        },
                        new
                        {
                            Id = new Guid("110fc2ec-7d7d-4955-9505-0d962e0c1deb"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Minh",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2021, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Le",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0018",
                            Type = 2,
                            Username = "minhle"
                        },
                        new
                        {
                            Id = new Guid("56d73f5a-91be-4552-b356-dab3367315f1"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thao",
                            Gender = 2,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Phan",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0019",
                            Type = 2,
                            Username = "thaophan"
                        },
                        new
                        {
                            Id = new Guid("480826b4-b3f7-4838-b830-1a673a508fdb"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1994, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Long",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2023, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Dang",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0020",
                            Type = 2,
                            Username = "longdang"
                        },
                        new
                        {
                            Id = new Guid("4f8327a0-c573-4e28-bdce-c05b28aaab07"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Quynh",
                            Gender = 2,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2020, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Pham",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0021",
                            Type = 2,
                            Username = "quynhpham"
                        },
                        new
                        {
                            Id = new Guid("4a7ee807-4881-4b19-9fa5-4caefa6ef653"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1989, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dung",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2022, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ly",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0022",
                            Type = 2,
                            Username = "dungly"
                        },
                        new
                        {
                            Id = new Guid("aae93aa5-632c-4101-ac5a-ae3bf7c1b031"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1995, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Huong",
                            Gender = 2,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Do",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0023",
                            Type = 2,
                            Username = "huongdo"
                        },
                        new
                        {
                            Id = new Guid("d32543f8-1346-4c0d-af20-17edf8149d75"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Phong",
                            Gender = 1,
                            IsActive = true,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2021, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hoang",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0024",
                            Type = 2,
                            Username = "phonghoang"
                        },
                        new
                        {
                            Id = new Guid("43fcafa3-be42-4100-91d2-6390b1a81780"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tram",
                            Gender = 2,
                            IsActive = false,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ngo",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0025",
                            Type = 2,
                            Username = "tramngo"
                        },
                        new
                        {
                            Id = new Guid("9b05c83e-410f-4ca6-aa7b-98c1bc63b6f2"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Khoi",
                            Gender = 1,
                            IsActive = false,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2019, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Phan",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0026",
                            Type = 2,
                            Username = "khoiphan"
                        },
                        new
                        {
                            Id = new Guid("43ea65e7-4878-45dc-b730-47c3b2dba729"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1993, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Yen",
                            Gender = 2,
                            IsActive = false,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lam",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0027",
                            Type = 2,
                            Username = "yenlam"
                        },
                        new
                        {
                            Id = new Guid("6a527ed0-cf45-4076-b930-d0183e274cc4"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Vinh",
                            Gender = 1,
                            IsActive = false,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2018, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Dinh",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0028",
                            Type = 2,
                            Username = "vinhdinh"
                        },
                        new
                        {
                            Id = new Guid("18c5c4c2-e04a-4e9f-8c83-370e5a03ca1c"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1995, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lan",
                            Gender = 2,
                            IsActive = false,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bui",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0029",
                            Type = 2,
                            Username = "lanbui"
                        },
                        new
                        {
                            Id = new Guid("a2786e5b-9b10-4c24-92a0-915d686d1086"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1988, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tien",
                            Gender = 1,
                            IsActive = false,
                            IsPasswordUpdated = true,
                            JoinedDate = new DateTimeOffset(new DateTime(2016, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Vu",
                            Location = 2,
                            Password = "UG9KspzI+vFB6XbUYNTk5THtu1iPQruEIU0jEPFNrlzrBs/kgX/Ol0E/HXyjJrcV",
                            StaffCode = "SD0030",
                            Type = 2,
                            Username = "tienvu"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Asset", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Entities.Category", null)
                        .WithMany("Assets")
                        .HasForeignKey("CategoryId1");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Category", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
