using System.ComponentModel.DataAnnotations.Schema;
using AssetManagement.Domain.Enums;

namespace AssetManagement.Domain.Entities
{
    public class User : BaseEntity
    {
        /// <summary>
        /// Auto-generated by format: SD0001
        /// </summary>
        public string StaffCode { get; set; } = null!;

        public string FirstName { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;

        [NotMapped]
        public string FullName => $"{FirstName} {LastName}";

        /// <summary>
        /// Auto-generated by format: binhnv, binhnv1
        /// </summary>
        public required string Username { get; set; }

        public required string Email { get; set; }

        public required string Password { get; set; }
        public bool IsPasswordUpdated { get; set; }

        public DateTime? DateOfBirth { get; set; }

        public DateTimeOffset JoinedDate { get; set; }

        /// <summary>
        /// User's type
        /// </summary>
        public UserTypeEnum Type { get; set; }

        /// <summary>
        /// Location
        /// </summary>
        public LocationEnum Location { get; set; }

        public GenderEnum Gender { get; set; }
    }
}